version: '3.8'

services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  minio:
    image: minio/minio:RELEASE.2025-10-15T17-29-55Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    expose:
      - "9000"
      - "9001"
    restart: unless-stopped

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      - minio
    restart: unless-stopped
    networks:
      - internal

volumes:
  minio_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
